<?php

use Illuminate\Support\Facades\Route;

// This file is typically generated by Laravel Breeze
// These are placeholder routes - install Breeze for full authentication scaffolding:
// php artisan breeze:install

Route::middleware('guest')->group(function () {
    // Login routes will be added by Breeze
    // Route::get('/login', [LoginController::class, 'create'])->name('login');
    // Route::post('/login', [LoginController::class, 'store']);

    // Register routes will be added by Breeze
    // Route::get('/register', [RegisterController::class, 'create'])->name('register');
    // Route::post('/register', [RegisterController::class, 'store']);

    // Password reset routes will be added by Breeze
});

Route::middleware('auth')->group(function () {
    // Logout route will be added by Breeze
    // Route::post('/logout', [LogoutController::class, 'destroy'])->name('logout');
});
